In [ ]:
Задание_1.
Контрольная работа состоит из пяти вопросов. 
На каждый вопрос приведено четыре варианта ответа, 
один из которых правильный. 
Составьте закон распределения числа правильных ответов при простом угадывании. 
Найдите M(X), D(X).



In [ ]:
Пусть  𝑋  — колличество правильно угаданных ответов. Вот ее закон распределения:
        𝑥 		0				1				2				3				4				5
𝑃(𝑋=𝑥)	0.2373046875	0.3955078125	0.26367187		0.087890625		0.0146484375	0.0009765625


<img spc="Task_1_1.jpg"/>

<img src="Task_1_1.jpg" style ="width:300 px; heigth:300 px"/>


In [2]:
import numpy as np
x_values = np.arange(0, 6)

print(x_values)

[0 1 2 3 4 5]


In [3]:
x_probabilities = np.array([0.2373046875, 0.3955078125, 0.26367187, 0.087890625, 0.0146484375, 
                            0.0009765625])

In [4]:
m = x_values.dot(x_probabilities)

print(m)

1.24999999


In [ ]:
При вычислении вручную на калькуляторе получилось mX = 1.25, а dX = 0.9375
(не совпало, если вводить m (1.25 - совпадение результата дисперсии ближе)!!отличие почти 0.1 при m )
В данном примере Биномиальный закон распределения случайной величины и 
𝑀(𝑋)=𝑛𝑝 = 5*0.25 = 1.25
𝐷(𝑋)=𝑛𝑝(1−𝑝) = 1.25*0.75=0.9375

In [18]:
dx_values = (x_values - 1.25)**2
d = dx_values.dot(x_probabilities)

print(dx_values)
print(d)

[ 1.5625  0.0625  0.5625  3.0625  7.5625 14.0625]
0.9374999971875


In [16]:
dx_values = x_values - m
print(dx_values)


[-0.9375  0.0625  1.0625  2.0625  3.0625  4.0625]


In [17]:
d2x_values = dx_values**2
print(d2x_values)

[8.78906245e-01 3.90625035e-03 1.12890626e+00 4.25390626e+00
 9.37890627e+00 1.65039063e+01]


<img src="Task_1_2.jpg"/>
